name: Build

on:
  push:
    branches:
      - 'main'
      - 'v*'
    tags:
      - 'v*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'main'
      - 'v*'
jobs:
  macos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [ macos, windows, linux ]
    steps:
      - uses: actions/checkout@v2
      - run: make build-${{ matrix.type }}
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ matrix.type }}.zip
